### PR TITLE
DFTB read out

### PR DESCRIPTION
**Pull request by felixplasser**
Hi @comecattin,

It looks like you made some changes to the way DFTB+ is handled by TheoDORE. Would you say these are general features that should be taken into the main TheoDORE distribution? The DFTB+ interface was only ever quite rudimentary.

-Felix

### CODE REVIEW

**Comment by comecattin** [comment]
Hi,

I’ve made these changes in the context of a numerical project in my Master. I think the changes done can be taken into account into the main TheoDORE distribution. The DFTB+ interface should now be more stable and more flexible than before. Tell me if you have further questions.

Best,

Cattin Côme
Représentant des élèves Sciences de la Matière, Chimie
ENS de Lyon
perso.ens-lyon.fr/come.cattin/ <https://perso.ens-lyon.fr/come.cattin/>

**Comment by comecattin** [comment]
Hi @felixplasser,

I’ve made these changes in the context of a numerical project in my Master. I think the changes done can be taken into account into the main TheoDORE distribution. The DFTB+ interface should now be more stable and more flexible than before. Tell me if you have further questions.

Best,

Côme

**Comment by felixplasser** [comment]
Hi @comecattin ,

I just had a look at this. The code looks nice! But it crashes with the available example I have
https://github.com/felixplasser/theodore-test/tree/master/STANDARD/biphenyl.tddftb

The reason is that I don't have the `band.out` file. Are you able to provide an example with all the required files? Then i can finalise the merge.

If you are happy with it, then I can add your name to the list of contributors in the header. I like to keep a list of everyone who contributed some code.

**Comment by felixplasser** [comment]
I'll close this for now. It seems like this would need some additions in terms of documentation and testing to actually make this suitable for including it with the main distribution.

**Comment by comecattin** [comment]
Hi @felixplasser,
Sorry for my late answer !
You're right, this will need some addition. On top of that the `band.out` file is generated with a developer version of dftb+. I'm not sure it is out yet...

**Pull request closed without merging**
